language: php

php:
  - 5.2
  - 5.3
  - 5.4

matrix:
  include:
    - php: 5.2
      dist: precise
    - php: 5.3
      dist: precise
  allow_failures:
    - php: 5.2
    - php: 5.3

before_script:
- composer install

env:
 - AMC_USERNAME="test:Shaffer Corp SBX" AMC_SECRET=4403235623ba9d64b0d8d5b3315fdc7c AMC_REPORTSUITE=shaffertest AMC_ENDPOINT=api-sbx1.omniture.com
